"""add email and google_id to user

Revision ID: c236f26bb0a1
Revises: 001_add_profile_pic_url
Create Date: 2026-07-05 15:05:42.264211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c236f26bb0a1'
down_revision: Union[str, Sequence[str], None] = '001_add_profile_pic_url'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('users', sa.Column('email', sa.String(length=320), nullable=True))
    op.add_column('users', sa.Column('google_id', sa.String(length=255), nullable=True))
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.create_unique_constraint('uq_users_email', 'users', ['email'])
    op.create_unique_constraint('uq_users_google_id', 'users', ['google_id'])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index(op.f('idx_users_tenant_role'), 'users', ['tenant_id', 'role'], unique=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_column('users', 'google_id')
    op.drop_column('users', 'email')
    op.create_index(op.f('idx_trucks_tenant'), 'trucks', ['tenant_id'], unique=False)
    op.alter_column('trucks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('tenants', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.add_column('orders', sa.Column('price_per_kg', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.create_index(op.f('idx_orders_tenant'), 'orders', ['tenant_id'], unique=False)
    op.create_index(op.f('idx_orders_retailer_date'), 'orders', ['retailer_id', sa.literal_column('delivery_date DESC')], unique=False)
    op.alter_column('orders', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('orders', 'delivery_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               nullable=False)
    op.alter_column('orders', 'status',
               existing_type=sa.String(),
               type_=postgresql.ENUM('pending', 'confirmed', 'in_transit', 'delivered', 'cancelled', name='order_status'),
               existing_nullable=True,
               existing_server_default=sa.text("'pending'::order_status"))
    op.alter_column('orders', 'total_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
    op.alter_column('orders', 'retailer_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('orders', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_index(op.f('idx_khata_tenant'), 'khata_transactions', ['tenant_id'], unique=False)
    op.create_index(op.f('idx_khata_retailer'), 'khata_transactions', ['retailer_id', sa.literal_column('created_at DESC')], unique=False)
    op.alter_column('khata_transactions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('idx_iot_truck_time'), 'iot_readings', ['truck_id', sa.literal_column('recorded_at DESC')], unique=False)
    op.alter_column('iot_readings', 'alert_triggered',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('iot_readings', 'truck_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('idx_inventory_tenant'), 'inventory', ['tenant_id'], unique=False)
    op.alter_column('error_logs', 'error_message',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('error_logs', 'error_type',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('error_logs', 'source',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('error_logs', 'id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.create_index(op.f('idx_classification_logs_source'), 'classification_logs', ['order_source', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_classification_logs_intent'), 'classification_logs', ['intent', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_classification_logs_confidence'), 'classification_logs', ['confidence'], unique=False)
    op.alter_column('classification_logs', 'order_source',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('classification_logs', 'message_snippet',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('classification_logs', 'id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.create_index(op.f('idx_ai_forecasts_tenant_date'), 'ai_forecasts', ['tenant_id', 'target_date'], unique=False)
    op.create_index(op.f('idx_ai_forecasts_embedding'), 'ai_forecasts', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_l2_ops'}, postgresql_using='hnsw')
    op.alter_column('ai_forecasts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    # ### end Alembic commands ###
